#!/bin/bas#!/bin/bash
chmod --reference olleh hell#!/bin/bash
chmod --reference olleh hell#!/bin/bash
chmod --reference olleh hell#!/bin/bash
chmod --reference olleh helloooohmod --reference olleh hello
